{% set version = "0.5.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nanoarrow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nanoarrow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nanoarrow/nanoarrow_{{ version }}.tar.gz
  sha256: 25c0372dc921645dc96d3f039531fe7bc164b34df7f98722590efeb14ab3a265

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]

test:
  commands:
    - $R -e "library('nanoarrow')"           # [not win]
    - "\"%R%\" -e \"library('nanoarrow')\""  # [win]

about:
  home: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  summary: Provides an 'R' interface to the 'nanoarrow' 'C' library and the 'Apache Arrow' application binary interface. Functions to import and export 'ArrowArray', 'ArrowSchema', and 'ArrowArrayStream' 'C' structures to and from 'R' objects are provided alongside helpers to facilitate zero-copy data transfer among 'R'
    bindings to libraries implementing the 'Arrow' 'C' data interface.
  license_family: APACHE
  license_file: LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nanoarrow
# Title: Interface to the 'nanoarrow' 'C' Library
# Version: 0.3.0.1
# Authors@R: c( person(given = "Dewey", family = "Dunnington", role = c("aut", "cre"), email = "dewey@dunnington.ca", comment = c(ORCID = "0000-0002-9415-4582")), person("Apache Arrow", email = "dev@arrow.apache.org", role = c("aut", "cph")), person("Apache Software Foundation", email = "dev@arrow.apache.org", role = c("cph")) )
# Description: Provides an 'R' interface to the 'nanoarrow' 'C' library and the 'Apache Arrow' application binary interface. Functions to import and export 'ArrowArray', 'ArrowSchema', and 'ArrowArrayStream' 'C' structures to and from 'R' objects are provided alongside helpers to facilitate zero-copy data transfer among 'R' bindings to libraries implementing the 'Arrow' 'C' data interface.
# License: Apache License (>= 2)
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# URL: https://github.com/apache/arrow-nanoarrow
# BugReports: https://github.com/apache/arrow-nanoarrow/issues
# Suggests: arrow (>= 9.0.0), bit64, blob, hms, rlang, testthat (>= 3.0.0), tibble, vctrs, withr
# Config/testthat/edition: 3
# Config/build/bootstrap: TRUE
# NeedsCompilation: yes
# Packaged: 2023-12-08 01:16:31 UTC; deweydunnington
# Author: Dewey Dunnington [aut, cre] (<https://orcid.org/0000-0002-9415-4582>), Apache Arrow [aut, cph], Apache Software Foundation [cph]
# Maintainer: Dewey Dunnington <dewey@dunnington.ca>
# Repository: CRAN
# Date/Publication: 2023-12-08 04:50:02 UTC
